### ISSUE TITLE
online link

### ISSUE THREAD

**Issue by EngelschallNikolaus** [rstropek-teaching/form-validation-quiz-4ahif-EngelschallNikolaus#1]
Dear Mr. Stropek, 

hereby I provide you a link where my solution of the form validation exercise can be tried out online.

https://rawgit.com/rstropek-teaching/form-validation-quiz-4ahif-EngelschallNikolaus/master/dist/index.html
Greetings,
Nikolaus Engelschall

**Comment by rstropek** [comment]
@EngelschallNikolaus Thank you for your homework. It already looks promising.

However, I have found one issue. Here is a repro for the bug:

* Open the link you provided
* Click on *Subscribe to Newsletter*
* The error *Email is mandatory...* does **not** appear, although it should
* Click on *Subscribe to Newsletter* a second time
* Now the error *Email is mandatory...* appears

I think, the problem is that you validate the email on **blur**. Maybe you should consider handling a different event for the checkbox.

Greetings,
Rainer Stropek

**Comment by EngelschallNikolaus** [comment]
Thank you for the feedback. The last time I tried it out, it worked, but I got the same error now. I already fixed the bug by replacing "blur" with "on click". It should work like a charm now.

Have a nice day,
Nikolaus Engelschall

**Comment by rstropek** [comment]
Works perfectly fine now, thank you.

Greetings,
Rainer Stropek.
